### ISSUE TITLE
CloudReadyを焼いてChromiumOSを体験しよう！

### ISSUE THREAD

**Issue by blank71** [drikin/guruwiki#1]
たぶんChromeOSと違うのでGooglePlayが使えないのに注意です。

- [Does CloudReady support the Google Play Store & Android Apps?](https://neverware.zendesk.com/hc/en-us/articles/221303948-Does-CloudReady-support-the-Google-Play-Store-Android-Apps-)

> Google has added support for running Android apps via integration with the Google Play Store on many Chromebooks. Due to multiple legal and technical constraints, this functionality is not available on CloudReady. Currently, Neverware has no plans to add this functionality.

**Comment by blank71** [comment]
- [古いノートPCをChromebookとして復活させてくれるアプリ『CloudReady』](https://www.lifehacker.jp/2015/11/151113cloudready_chromebook.html)

- [Install CloudReady ](https://guide.neverware.com/install-cloudready/)

- [「CloudReady」で古いPC/MacをChromebookに](http://cloud-work.net/chromium-os/cloudready/)

**Comment by Blank71** [comment]
https://www.xda-developers.com/linux-app-support-older-chrome-os-devices/

**Comment by blank71** [comment]
実際に検証をまだしていないので、できるかどうかは分からないので、自己責任でお願いします。

準備：USBメモリ(8GBか16GB)
　　　ブートするPC

手順

1. [https://www.neverware.com/](https://www.neverware.com/) にアクセスし、HomeEditionのページを開き、Windowsの場合はUSB Makerを選択。DLされたファイルは(cloudready-usb-maker.exe)だと思う。

2.(cloudready-usb-maker.exe)を起動。その中に提示してある手順に従い、指定のUSBメモリにCloudReadyをインストールする。

3.BIOSでPCの起動ドライブの優先順位を変更する。(一番最初にUSB Flash Drive、二番目に従来のドライブが来るようにするのが望ましい。)

4.USBメモリをPCにさして起動する。CloudReadyのアイコンが出てきたらたぶん起動成功。提示された内容に従い、初期設定をする。

5,通知エリアに(Install CloudReady)という項目があるが、それを選択すると今まで使ってたドライブに上書きされて、従来のデータが消去されてしまうので注意。

**Comment by blank71** [comment]
- Dual Bootを模索してみる。
[Can I dual boot CloudReady with another OS?](https://neverware.zendesk.com/hc/en-us/articles/208640347-Can-I-dual-boot-CloudReady-with-another-OS-)
